version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    todonco:
      image: 'mysql:latest'
      environment:
        MYSQL_ROOT_PASSWORD: null
        MYSQL_DATABASE: main
      ports:
        # To allow the host machine to access the ports below, modify the lines below.
        - '3306'
        # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
        # - ./docker/db/data:/var/lib/postgresql/data:rw
        ###< doctrine/doctrine-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  db-data: ###< doctrine/doctrine-bundle ###
